# Deploys a terraform infrastructure to !PRODUCTION! whenever a 
# branch is pushed to main.
#
# Note: You should use a branch protection rule to enforce that
# main is only pushed via a PR per the team git standards

name: Tagging Terraform with Yor
on:

# switch to this trigger to disable this job
#  workflow_dispatch:

  pull_request:
    types: [opened, reopened, synchronize]
    # paths:
    #   - "**.tf"
    #   - "**.tfvars"
  
jobs:
  tf-prod-cicd:
    name: Infrastructure Tagging Jobs
    runs-on: ubuntu-latest

    steps:

      # checkout the repo (complete, not shallow, for yor's blame checking)
      - name: Checkout Repo
        uses: actions/checkout@v4
        id: checkoutrepo
        with:
          # this is required for yor tagging. yor needs historical information
          # to make decissions about git_* tags (unshallow)
          fetch-depth: 0
          #ref: ${{ github.event.pull_request.head.ref }}

      # https://github.com/crazy-max/ghaction-import-gpg?tab=readme-ov-file
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: importgpgkey
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      # Insert tags into TF resources, custom tages from .tag_config.yml and the
      # tag groups for yor and git. Note, this happens during the work flow and
      # puts the remote main branch one commit ahead of your local main branch.
      # So, after the workflow runs, you need to git pull your local main branch
      # (or completely destry ant git checkout the repo again)
      - name: TF tagging (yor)
        uses: bridgecrewio/yor-action@main
        id: tftaggingyor
        with:
          parsers: Terraform
          tag_groups: git,code2cloud
          tags: git_org,git_repo,yor_trace
          #tag_prefix: 'technical:' # will turn the back on after fix to https://github.com/bridgecrewio/yor/issues/492
          commit_changes: false

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automated Yor tagging"
          commit_options: '-S${{ steps.importgpgkey.outputs.fingerprint }}'
          commit_user_name: ${{ steps.importgpgkey.outputs.name }}
          commit_user_email: ${{ steps.importgpgkey.outputs.email }}
          commit_author: ${{ steps.importgpgkey.outputs.name }} <${{ steps.importgpgkey.outputs.email }}>
